export const PART_CATALOG = {
  heads: [
    { key: "cube", variant: 0 },
    { key: "bubble", variant: 1 },
    { key: "visor", variant: 2 },
    { key: "antenna", variant: 3 },
    { key: "cat", variant: 4 },
    { key: "crown", variant: 5 },
    { key: "helmet", variant: 6 },
    { key: "star", variant: 7 },
    { key: "cloud", variant: 8 },
    { key: "rocket", variant: 9 },
    { key: "owl", variant: 10 },
    { key: "donut", variant: 11 },
    { key: "frog", variant: 12 },
    { key: "tv", variant: 13 },
    { key: "dice", variant: 14 },
    { key: "beetle", variant: 15 },
    { key: "kite", variant: 16 },
    { key: "pumpkin", variant: 17 },
  ],
  bodies: [
    { key: "chest", variant: 0, engine: false },
    { key: "tank", variant: 1, engine: false },
    { key: "shield", variant: 2, engine: false },
    { key: "orb", variant: 3, engine: false },
    { key: "speaker", variant: 4, engine: false },
    { key: "safe", variant: 5, engine: false },
    { key: "rocket", variant: 6, engine: false },
    { key: "gift", variant: 7, engine: false },
    { key: "engine", variant: 8, engine: true },
    { key: "jet", variant: 9, engine: true },
    { key: "arcade", variant: 10, engine: false },
    { key: "jelly", variant: 11, engine: false },
    { key: "backpack", variant: 12, engine: false },
    { key: "lantern", variant: 13, engine: false },
    { key: "teapot", variant: 14, engine: false },
    { key: "mailbox", variant: 15, engine: false },
    { key: "reactor", variant: 16, engine: true },
    { key: "sub", variant: 17, engine: true },
  ],
  arms: [
    { key: "claw", variant: 0 },
    { key: "spring", variant: 1 },
    { key: "paddle", variant: 2 },
    { key: "wing", variant: 3 },
    { key: "mitt", variant: 4 },
    { key: "wand", variant: 5 },
    { key: "hook", variant: 6 },
    { key: "drum", variant: 7 },
    { key: "brush", variant: 8 },
    { key: "fan", variant: 9 },
    { key: "balloon", variant: 10 },
    { key: "ribbon", variant: 11 },
    { key: "grabber", variant: 12 },
    { key: "laser", variant: 13 },
    { key: "bubble", variant: 14 },
    { key: "trumpet", variant: 15 },
    { key: "noodle", variant: 16 },
    { key: "pixel", variant: 17 },
  ],
  legs: [
    { key: "walker", variant: 0 },
    { key: "boots", variant: 1 },
    { key: "wheels", variant: 2 },
    { key: "treads", variant: 3 },
    { key: "hover", variant: 4 },
    { key: "springs", variant: 5 },
    { key: "stompers", variant: 6 },
    { key: "pogo", variant: 7 },
    { key: "skates", variant: 8 },
    { key: "paws", variant: 9 },
    { key: "spider", variant: 10 },
    { key: "stilts", variant: 11 },
    { key: "fins", variant: 12 },
    { key: "skis", variant: 13 },
    { key: "moon", variant: 14 },
    { key: "tentacle", variant: 15 },
    { key: "magnet", variant: 16 },
    { key: "rollers", variant: 17 },
  ],
};
