export const CHARACTER_MODES = Object.freeze(["robot", "astronaut", "dragon"]);

function createPartList(keys) {
  return keys.map((key, variant) => ({ key, variant }));
}

function createBodyList(keys, engineKeys = []) {
  const engineSet = new Set(engineKeys);
  return keys.map((key, variant) => ({ key, variant, engine: engineSet.has(key) }));
}

const ROBOT_PART_CATALOG = Object.freeze({
  heads: createPartList([
    "cube",
    "bubble",
    "visor",
    "antenna",
    "cat",
    "crown",
    "helmet",
    "star",
    "cloud",
    "rocket",
    "owl",
    "donut",
    "frog",
    "tv",
    "dice",
    "beetle",
    "kite",
    "pumpkin",
  ]),
  bodies: createBodyList(
    [
      "chest",
      "tank",
      "shield",
      "orb",
      "speaker",
      "safe",
      "rocket",
      "gift",
      "engine",
      "jet",
      "arcade",
      "jelly",
      "backpack",
      "lantern",
      "teapot",
      "mailbox",
      "reactor",
      "sub",
    ],
    ["engine", "jet", "reactor", "sub"],
  ),
  arms: createPartList([
    "claw",
    "spring",
    "paddle",
    "wing",
    "mitt",
    "wand",
    "hook",
    "drum",
    "brush",
    "fan",
    "balloon",
    "ribbon",
    "grabber",
    "laser",
    "bubble",
    "trumpet",
    "noodle",
    "pixel",
  ]),
  legs: createPartList([
    "walker",
    "boots",
    "wheels",
    "treads",
    "hover",
    "springs",
    "stompers",
    "pogo",
    "skates",
    "paws",
    "spider",
    "stilts",
    "fins",
    "skis",
    "moon",
    "tentacle",
    "magnet",
    "rollers",
  ]),
});

const ASTRONAUT_PART_CATALOG = Object.freeze({
  heads: createPartList([
    "eva",
    "ranger",
    "orbital",
    "starlens",
    "comms",
    "halo",
    "beacon",
    "cosmo",
    "visorx",
    "nebula",
    "cadet",
    "atlas",
    "quartz",
    "pilot",
    "satellite",
    "lumen",
    "eclipse",
    "zenith",
  ]),
  bodies: createBodyList(
    [
      "suit",
      "capsule",
      "shuttle",
      "cargo",
      "thruster",
      "orbiter",
      "lander",
      "booster",
      "reactor",
      "comet",
      "stasis",
      "astroforge",
      "plasma",
      "airstack",
      "gravity",
      "ion",
      "cosmopod",
      "warp",
    ],
    ["thruster", "orbiter", "booster", "warp"],
  ),
  arms: createPartList([
    "gauntlet",
    "scanner",
    "magclaw",
    "jetfin",
    "patch",
    "tractor",
    "hookline",
    "drone",
    "beaconarm",
    "flare",
    "holo",
    "relay",
    "grip",
    "laserhand",
    "bubbletool",
    "antennaarm",
    "coil",
    "pixelarm",
  ]),
  legs: createPartList([
    "moonboot",
    "thrusterboots",
    "gyro",
    "crawler",
    "hoverpad",
    "springstep",
    "crater",
    "probe",
    "skater",
    "pawguard",
    "spiderpod",
    "stiltpod",
    "finfoot",
    "skid",
    "lunar",
    "tentagrip",
    "maglock",
    "rollerpod",
  ]),
});

const DRAGON_PART_CATALOG = Object.freeze({
  heads: createPartList([
    "wyrm",
    "spike",
    "ember",
    "scale",
    "jade",
    "crownhorn",
    "obsidian",
    "storm",
    "mist",
    "meteor",
    "elder",
    "fang",
    "toad",
    "rune",
    "gem",
    "beetlesnout",
    "kitewing",
    "gourd",
  ]),
  bodies: createBodyList(
    [
      "plate",
      "ridge",
      "carapace",
      "core",
      "drumfire",
      "vault",
      "comet",
      "hoard",
      "furnace",
      "jetflame",
      "totem",
      "slime",
      "saddle",
      "lanternbelly",
      "kettle",
      "mail",
      "volcano",
      "subscale",
    ],
    ["furnace", "jetflame", "volcano", "comet"],
  ),
  arms: createPartList([
    "talon",
    "coil",
    "paddleclaw",
    "wingclaw",
    "paw",
    "wandflame",
    "hooktalon",
    "drumbeater",
    "brushtail",
    "fanwing",
    "bubbleclaw",
    "ribbonscale",
    "grabtalon",
    "laserfang",
    "mistclaw",
    "trumphorn",
    "noodleclaw",
    "pixeltalon",
  ]),
  legs: createPartList([
    "stalker",
    "hoof",
    "wheelclaw",
    "track",
    "glide",
    "springclaw",
    "stomper",
    "pogohoof",
    "skateclaw",
    "pawpad",
    "spiderclaw",
    "stiltclaw",
    "finclaw",
    "skiclaw",
    "moonclaw",
    "tentaclaw",
    "magnethoof",
    "rollerclaw",
  ]),
});

export const PART_CATALOGS_BY_MODE = Object.freeze({
  robot: ROBOT_PART_CATALOG,
  astronaut: ASTRONAUT_PART_CATALOG,
  dragon: DRAGON_PART_CATALOG,
});

export const PART_CATALOG = PART_CATALOGS_BY_MODE.robot;
